In [1]:
import torch
import numpy as np

In [2]:
#Question 1
tensor = torch.arange(9).reshape(3, 3)
print("Original Tensor:")
print(tensor)
print()

reshaped_tensor = tensor.view(1, 9)
print("Reshaped Tensor (1x9):")
print(reshaped_tensor)
print()

viewed_tensor = reshaped_tensor.view(3, 3)
print("Viewed Tensor (3x3):")
print(viewed_tensor)
print()

stacked_tensor = torch.stack([tensor, tensor], dim=0)
print("Stacked Tensor (2 stacked 3x3 tensors):")
print(stacked_tensor)
print()

tensor_with_extra_dim = torch.rand(1, 3, 3, 1)
print("Tensor with Extra Dimension:")
print(tensor_with_extra_dim)
squeezed_tensor = tensor_with_extra_dim.squeeze()
print("Squeezed Tensor (removed size 1 dimensions):")
print(squeezed_tensor)
print()

unsqueezed_tensor = squeezed_tensor.unsqueeze(0)
print("Unsqueezed Tensor (adds a dimension at index 0):")
print(unsqueezed_tensor)
print()

unsqueezed_tensor_2 = squeezed_tensor.unsqueeze(2)
print("Unsqueezed Tensor at index 2 (adds a dimension at index 2):")
print(unsqueezed_tensor_2)

Original Tensor:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Reshaped Tensor (1x9):
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

Viewed Tensor (3x3):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Stacked Tensor (2 stacked 3x3 tensors):
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

Tensor with Extra Dimension:
tensor([[[[0.9059],
          [0.3458],
          [0.9619]],

         [[0.0979],
          [0.1330],
          [0.7136]],

         [[0.0179],
          [0.3320],
          [0.9477]]]])
Squeezed Tensor (removed size 1 dimensions):
tensor([[0.9059, 0.3458, 0.9619],
        [0.0979, 0.1330, 0.7136],
        [0.0179, 0.3320, 0.9477]])

Unsqueezed Tensor (adds a dimension at index 0):
tensor([[[0.9059, 0.3458, 0.9619],
         [0.0979, 0.1330, 0.7136],
         [0.0179, 0.3320, 0.9477]]])

Unsqueezed Tensor at index 2 (adds a dimension at index 2):
tensor([[[0.9059],
         [0.3458

In [3]:
#Question 2
tensor = torch.randn(2, 3, 4)
print("Original Tensor (Shape: 2x3x4):")
print(tensor)
print()
permuted_tensor = tensor.permute(2, 1, 0)
print("Permuted Tensor (Shape: 4x3x2):")
print(permuted_tensor)
print()

print("Shape of original tensor:", tensor.shape)
print("Shape of permuted tensor:", permuted_tensor.shape)

Original Tensor (Shape: 2x3x4):
tensor([[[-0.0971, -0.7802,  2.7657,  0.4479],
         [ 0.4044, -0.2875, -1.6076, -0.1503],
         [ 0.7993, -1.0874,  0.5758, -1.0489]],

        [[ 1.9351, -0.1659, -0.1499,  0.6623],
         [-0.5155,  0.3859, -1.1291, -0.4433],
         [ 1.0693,  0.6857,  0.7279,  0.0786]]])

Permuted Tensor (Shape: 4x3x2):
tensor([[[-0.0971,  1.9351],
         [ 0.4044, -0.5155],
         [ 0.7993,  1.0693]],

        [[-0.7802, -0.1659],
         [-0.2875,  0.3859],
         [-1.0874,  0.6857]],

        [[ 2.7657, -0.1499],
         [-1.6076, -1.1291],
         [ 0.5758,  0.7279]],

        [[ 0.4479,  0.6623],
         [-0.1503, -0.4433],
         [-1.0489,  0.0786]]])

Shape of original tensor: torch.Size([2, 3, 4])
Shape of permuted tensor: torch.Size([4, 3, 2])


In [4]:
#Question 3
tensor = torch.tensor([[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]])
print(tensor[1, 2])

print(tensor[0,0:3])

tensor(7)
tensor([1, 2, 3])


In [5]:
#Question 4
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(numpy_array)
print()

tensor = torch.tensor(numpy_array)
print(tensor)
print()

back_to_numpy = tensor.numpy()
print(back_to_numpy)

[[1 2 3]
 [4 5 6]]

tensor([[1, 2, 3],
        [4, 5, 6]])

[[1 2 3]
 [4 5 6]]


In [6]:
#Question 5
random_tensor = torch.randn(7, 7)
print(random_tensor)
print()

tensor([[-0.5244,  0.8190, -0.0471,  0.6342, -0.5078, -0.1771, -0.7331],
        [ 1.9607,  0.0782,  0.1900,  0.7047,  0.7070, -0.9666, -0.5804],
        [ 0.3170,  0.6295,  0.5333, -0.2283,  0.5067, -0.4587, -0.6011],
        [ 0.5113,  0.4764, -2.3131,  1.7712,  0.2734, -0.8650, -0.3697],
        [ 1.0301,  0.1375,  0.0180,  1.0024, -0.1633, -0.1542, -0.7948],
        [ 1.0811,  1.2043,  0.6334, -0.4210, -0.3913,  0.8292,  0.1792],
        [-0.3141, -2.5052, -0.2016,  0.5982, -0.4330, -0.6082,  0.0057]])



In [7]:
#Question 6
random_tensor_1 = torch.randn(7, 7)
print(random_tensor_1)
print()

random_tensor_2 = torch.randn(1, 7)
print(random_tensor_1)
print()

random_tensor_3 = torch.matmul(random_tensor_1,random_tensor_2.T)
print(random_tensor_3)
print()

tensor([[ 1.5856e+00, -5.5983e-01,  1.0828e+00,  5.9335e-01, -5.8050e-01,
         -1.3865e+00, -5.6374e-01],
        [-1.7047e+00,  8.6551e-01, -3.0140e-01, -5.1794e-01, -1.8635e-01,
          1.0518e+00,  1.4174e-03],
        [-6.0320e-01, -1.6957e-01, -7.2799e-01, -5.1120e-01, -9.4256e-01,
          1.7032e+00, -1.3533e+00],
        [-1.4692e+00,  2.4106e-01, -2.5650e-01,  5.2394e-01, -7.5585e-01,
          1.3075e+00, -2.9158e-01],
        [ 9.1395e-01, -3.5503e-01, -7.4095e-01,  4.3294e-01,  5.7050e-02,
         -3.7117e-01,  9.3490e-01],
        [-5.9126e-01, -2.7612e-01, -8.7195e-01, -5.6376e-02,  2.8165e-02,
          5.1317e-01, -2.0627e+00],
        [ 1.8795e-02,  2.4273e+00,  2.8681e+00, -6.7425e-01,  4.9375e-01,
         -1.1936e+00,  5.2754e-01]])

tensor([[ 1.5856e+00, -5.5983e-01,  1.0828e+00,  5.9335e-01, -5.8050e-01,
         -1.3865e+00, -5.6374e-01],
        [-1.7047e+00,  8.6551e-01, -3.0140e-01, -5.1794e-01, -1.8635e-01,
          1.0518e+00,  1.4174e-03],
        

In [8]:
#Question 7
tensor_1 = torch.randn(2, 3)
tensor_2 = torch.randn(2, 3)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

tensor_1 = tensor_1.to(device)
tensor_2 = tensor_2.to(device)

print("Tensor 1:")
print(tensor_1)
print()

print("Tensor 2:")
print(tensor_2)

Using device: cuda
Tensor 1:
tensor([[-1.0722,  1.0127,  0.9785],
        [-0.2423,  1.0468, -1.7915]], device='cuda:0')

Tensor 2:
tensor([[-0.1332,  0.2946,  0.3068],
        [-0.2941,  1.0990,  0.7966]], device='cuda:0')


In [9]:
#Question 8
tensor_1 = torch.randn(2, 3)
tensor_2 = torch.randn(2, 3)

tensor_3 = torch.matmul(tensor_1,tensor_2.T)
print(tensor_3)

tensor([[ 1.9162,  2.2982],
        [-0.4365, -1.5560]])


In [11]:
#Question 9
tensor_1 = torch.randn(2, 3)
tensor_2 = torch.randn(2, 3)

tensor_3 = torch.matmul(tensor_1,tensor_2.T)
print(tensor_3)
print()

print("Maximum value in the tensor:",tensor_3.max())
print("Minimum value in the tensor:",tensor_3.min())

tensor([[-2.3380, -5.3110],
        [-0.8052, -0.3053]])

Maximum value in the tensor: tensor(-0.3053)
Minimum value in the tensor: tensor(-5.3110)


In [12]:
#Question 10
tensor_1 = torch.randn(2, 3)
tensor_2 = torch.randn(2, 3)

tensor_3 = torch.matmul(tensor_1,tensor_2.T)
print(tensor_3)
print()

print("Maximum value in the tensor:",tensor_3.argmax())
print("Minimum value in the tensor:",tensor_3.argmin())

tensor([[ 1.9157,  2.6251],
        [ 1.0652, -1.7684]])

Maximum value in the tensor: tensor(1)
Minimum value in the tensor: tensor(3)


In [13]:
#Question 11
torch.manual_seed(7)

tensor = torch.randn(1, 1, 1, 7)

print("Original Tensor:",tensor)
print()

squeezed_tensor = tensor.squeeze()
print("Squeezed Tensor:",squeezed_tensor)

Original Tensor: tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556]]]])

Squeezed Tensor: tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556])
